#if 0
//
// Generated by Microsoft (R) D3DX9 Shader Compiler 
//
//   fxc /nologo /Tvs_2_0 /EGlyphVS /VnVertexShader /Fhglyph.vs /Op glyph.fx
//
//
// Parameters:
//
//   float4 TextureSize;
//   float4 ViewportSize;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   ViewportSize c0       1
//   TextureSize  c1       1
//

    vs_2_0
    def c2, 0.5, 0, 0, 0
    dcl_position v0
    dcl_texcoord v1
    dcl_color v2
    dcl_color1 v3
    mov r0.xy, c0
    mad r0.xy, r0, -c2.x, v0
    mul r0.xy, r0, c0
    add oPos.xy, r0, r0
    rcp r0.x, c1.x
    mul oT0.x, r0.x, v1.x
    rcp r0.x, c1.y
    mul oT0.y, r0.x, v1.y
    mov oPos.zw, v0
    mov oD0, v2
    mov oD1, v3

// approximately 11 instruction slots used
#endif

const DWORD VertexShader[] =
{
    0xfffe0200, 0x0028fffe, 0x42415443, 0x0000001c, 0x00000074, 0xfffe0200, 
    0x00000002, 0x0000001c, 0x20000100, 0x0000006d, 0x00000044, 0x00010002, 
    0x00000001, 0x00000050, 0x00000000, 0x00000060, 0x00000002, 0x00000001, 
    0x00000050, 0x00000000, 0x74786554, 0x53657275, 0x00657a69, 0x00030001, 
    0x00040001, 0x00000001, 0x00000000, 0x77656956, 0x74726f70, 0x657a6953, 
    0x5f737600, 0x00305f32, 0x7263694d, 0x666f736f, 0x52282074, 0x33442029, 
    0x20395844, 0x64616853, 0x43207265, 0x69706d6f, 0x2072656c, 0xababab00, 
    0x05000051, 0xa00f0002, 0x3f000000, 0x00000000, 0x00000000, 0x00000000, 
    0x0200001f, 0x80000000, 0x900f0000, 0x0200001f, 0x80000005, 0x900f0001, 
    0x0200001f, 0x8000000a, 0x900f0002, 0x0200001f, 0x8001000a, 0x900f0003, 
    0x02000001, 0x80030000, 0xa0e40000, 0x04000004, 0x80030000, 0x80e40000, 
    0xa1000002, 0x90e40000, 0x03000005, 0x80030000, 0x80e40000, 0xa0e40000, 
    0x03000002, 0xc0030000, 0x80e40000, 0x80e40000, 0x02000006, 0x80010000, 
    0xa0000001, 0x03000005, 0xe0010000, 0x80000000, 0x90000001, 0x02000006, 
    0x80010000, 0xa0550001, 0x03000005, 0xe0020000, 0x80000000, 0x90550001, 
    0x02000001, 0xc00c0000, 0x90e40000, 0x02000001, 0xd00f0000, 0x90e40002, 
    0x02000001, 0xd00f0001, 0x90e40003, 0x0000ffff
};
